version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=hackathon_app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=your-secret-key-here
      - DATABASE_URL=postgresql://hackathon:test123@db:5432/hackathon
      - SQLALCHEMY_DATABASE_URI=postgresql://hackathon:test123@db:5432/hackathon
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=hackathon
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=hackathon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:

networks:
  hackathon-network:
    driver: bridge 