version: '3.8'

services:
  web:
    build: .
    ports:
      - "10000:5000"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/hackathon
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/hackathon
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hackathon
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data:

networks:
  hackathon-network:
    driver: bridge 