services:
  - type: web
    name: hackathon-platform
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hackathon_app:app
    envVars:
      - key: FLASK_APP
        value: hackathon_app.py
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hackathon-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: hackathon-redis
          property: connectionString

databases:
  - name: hackathon-db
    databaseName: hackathon
    user: hackathon
    plan: free

services:
  - type: redis
    name: hackathon-redis
    plan: free
    ipAllowList: [] 